### ISSUE TITLE
请问如何安装

### ISSUE THREAD

**Issue by GiggleWang** [BigSweetPotatoStudio/HyperChat#3]
你好，可以给一个安装的指南或者直接下载的软件吗，谢谢

**Comment by laopo001** [comment]
https://github.com/BigSweetPotatoStudio/HyperChat/releases/tag/0.0.6  这个就在github releases下载🤣。教程可以看看，mcp官网，https://modelcontextprotocol.io/introduction

**Comment by GiggleWang** [comment]
肥肠感谢
